### PR TITLE
added french translation

### PR DESCRIPTION
**Pull request by PatriceG**
Hi,
I've added a french translation for your cool module.
I've also modified my version (not included in this pull request) to display the values in a single row, on the top_bar region.

### CODE REVIEW

**Comment by slametps** [comment]
It would be great if you modify this module so user can select display mode via config the original or yours.

**Comment by slametps** [comment]
Can you post the screenshot of your modif result?

**Comment by PatriceG** [comment]
Here is a screenshot. I'll make the display mode configurable and will post a pull request.
system_stats_horizontal

**Comment by PatriceG** [comment]
I've added an 'orientation' attribute, with default value to 'vertical'

**Comment by slametps** [comment]
What if there are more info? My last pull-request, add new info (available disk) and not merged yet. Will It scroll left-right?

**Pull request closed without merging**
